const STORAGE_KEY='together-aa-v2',OLD_STORAGE_KEY='together-aa-v1';
const colors=['#dff35a','#ffb7a9','#a9d9ff','#c7b9ff','#ffd68a','#9de1ca'];
const categoryMeta={food:['餐飲','🍜'],transport:['交通','↗'],stay:['住宿','⌂'],ticket:['門票','◇'],other:['其他','✦']};
const demoState={tripName:'台南週末小旅行',currentUserId:'m1',members:[{id:'m1',name:'你'},{id:'m2',name:'小安'},{id:'m3',name:'晴晴'},{id:'m4',name:'阿哲'}],expenses:[{id:'e1',title:'巷口牛肉湯',amount:920,payerId:'m2',participantIds:['m1','m2','m3','m4'],category:'food',createdAt:'2026-08-24T09:20:00'},{id:'e2',title:'台北－台南高鐵',amount:5400,payerId:'m1',participantIds:['m1','m2','m3','m4'],category:'transport',createdAt:'2026-08-23T16:10:00'},{id:'e3',title:'老屋民宿兩晚',amount:6800,payerId:'m3',participantIds:['m1','m2','m3','m4'],category:'stay',createdAt:'2026-08-22T19:30:00'},{id:'e4',title:'十鼓文創園區',amount:1596,payerId:'m4',participantIds:['m1','m2','m3','m4'],category:'ticket',createdAt:'2026-08-22T14:00:00'}]};
let state=loadState(),currentFilter='all',toastTimer;const $=id=>document.getElementById(id);
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(OLD_STORAGE_KEY);return raw?JSON.parse(raw):structuredClone(demoState)}catch{return structuredClone(demoState)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function money(n){return `NT$ ${Math.round(n||0).toLocaleString('zh-TW')}`}
function member(id){return state.members.find(m=>m.id===id)}function initials(name){return name.slice(0,2)}
function escapeHtml(value){const d=document.createElement('div');d.textContent=String(value);return d.innerHTML}
function calculations(source=state){const paid=Object.fromEntries(source.members.map(m=>[m.id,0])),owed={...paid};source.expenses.forEach(e=>{paid[e.payerId]=(paid[e.payerId]||0)+e.amount;if(!e.participantIds.length)return;const share=e.amount/e.participantIds.length;e.participantIds.forEach(id=>owed[id]=(owed[id]||0)+share)});const balance=Object.fromEntries(source.members.map(m=>[m.id,(paid[m.id]||0)-(owed[m.id]||0)]));return{paid,owed,balance,total:source.expenses.reduce((sum,e)=>sum+e.amount,0)}}
function settlements(balance){const debtors=Object.entries(balance).filter(([,v])=>v<-.01).map(([id,v])=>({id,amount:-v})).sort((a,b)=>b.amount-a.amount),creditors=Object.entries(balance).filter(([,v])=>v>.01).map(([id,v])=>({id,amount:v})).sort((a,b)=>b.amount-a.amount),result=[];let d=0,c=0;while(d<debtors.length&&c<creditors.length){const amount=Math.min(debtors[d].amount,creditors[c].amount);result.push({from:debtors[d].id,to:creditors[c].id,amount});debtors[d].amount-=amount;creditors[c].amount-=amount;if(debtors[d].amount<.01)d++;if(creditors[c].amount<.01)c++}return result}
function render(){const calc=calculations(),me=state.currentUserId;$('tripName').textContent=state.tripName;$('expenseCount').textContent=`${state.expenses.length} 筆消費`;$('totalAmount').textContent=money(calc.total);$('myPaid').textContent=money(calc.paid[me]);$('myShare').textContent=money(calc.owed[me]);$('myPaidHint').textContent=calc.paid[me]&&calc.total?`占總花費 ${Math.round(calc.paid[me]/calc.total*100)}%`:'你目前沒有代墊';const balance=calc.balance[me]||0;$('myBalanceHint').textContent=Math.abs(balance)<1?'目前已經結清':balance>0?`應收回 ${money(balance)}`:`還需支付 ${money(-balance)}`;$('miniBars').innerHTML=state.members.map((m,i)=>`<i style="height:${18+(calc.paid[m.id]/Math.max(...Object.values(calc.paid),1))*34}px;opacity:${.45+i*.14}"></i>`).join('');renderExpenses();renderMembers(calc);renderSettlements(calc.balance);fillFormMembers();saveState()}
function renderExpenses(){const expenses=[...state.expenses].filter(e=>currentFilter==='all'||e.payerId===state.currentUserId).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));$('expenseList').innerHTML=expenses.map(e=>{const meta=categoryMeta[e.category]||categoryMeta.other;return `<article class="expense-item"><div class="category-icon category-${e.category}">${meta[1]}</div><div class="expense-info"><h3>${escapeHtml(e.title)}</h3><p>${escapeHtml(member(e.payerId)?.name||'已離開')} 先付 · ${e.participantIds.length} 人平均分攤</p></div><div class="expense-amount"><strong>${money(e.amount)}</strong><small>${meta[0]}</small></div><button class="delete-expense" data-delete-expense="${e.id}" title="刪除花費">刪除</button></article>`}).join('');$('emptyState').hidden=expenses.length>0}
function renderMembers(calc){$('memberList').innerHTML=state.members.map((m,i)=>{const balance=calc.balance[m.id]||0;return `<div class="member"><span class="avatar" style="background:${colors[i%colors.length]}">${escapeHtml(initials(m.name))}</span><div class="member-info"><strong>${escapeHtml(m.name)}${m.id===state.currentUserId?'（我）':''}</strong><span>已支付 ${money(calc.paid[m.id])}</span></div><span class="member-balance ${balance>=0?'positive':'negative'}">${Math.abs(balance)<1?'已結清':balance>0?`應收 ${money(balance)}`:`應付 ${money(-balance)}`}</span><button class="delete-member" data-delete-member="${m.id}" ${state.members.length===1?'disabled':''} title="刪除成員">×</button></div>`}).join('')}
function renderSettlements(balance){const list=settlements(balance);$('settlementList').innerHTML=list.length?list.map(s=>`<div class="settlement"><span>${escapeHtml(member(s.from)?.name||'已離開')}</span><span class="arrow">→</span><span>${escapeHtml(member(s.to)?.name||'已離開')}</span><strong>${money(s.amount)}</strong></div>`).join(''):'<div class="all-settled">大家都結清了，漂亮！</div>';$('copySettlementButton').disabled=!list.length}
function fillFormMembers(){$('expensePayer').innerHTML=state.members.map(m=>`<option value="${m.id}" ${m.id===state.currentUserId?'selected':''}>${escapeHtml(m.name)}${m.id===state.currentUserId?'（我）':''}</option>`).join('');$('participantGrid').innerHTML=state.members.map((m,i)=>`<label class="participant-option"><input type="checkbox" name="participants" value="${m.id}" checked><span class="avatar" style="background:${colors[i%colors.length]};width:25px;height:25px">${escapeHtml(initials(m.name))}</span>${escapeHtml(m.name)}</label>`).join('')}
function showToast(message,action){clearTimeout(toastTimer);$('toast').innerHTML=`${escapeHtml(message)}${action?' <button id="toastAction">復原</button>':''}`;$('toast').classList.add('show');if(action)$('toastAction').onclick=()=>{action();$('toast').classList.remove('show')};toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4000)}
function deleteExpense(id){const index=state.expenses.findIndex(e=>e.id===id);if(index<0)return;const removed=state.expenses.splice(index,1)[0];render();showToast('已刪除這筆花費',()=>{state.expenses.splice(index,0,removed);render()})}
function deleteMember(id){if(state.members.length===1){showToast('旅程至少需要保留一位成員');return}const target=member(id),paidCount=state.expenses.filter(e=>e.payerId===id).length,sharedCount=state.expenses.filter(e=>e.participantIds.includes(id)).length,detail=paidCount||sharedCount?`\n此成員支付 ${paidCount} 筆、參與分攤 ${sharedCount} 筆。支付的花費會刪除，其他花費則移除此人的分攤。`:'';if(!confirm(`確定刪除成員「${target.name}」嗎？${detail}`))return;state.members=state.members.filter(m=>m.id!==id);state.expenses=state.expenses.filter(e=>e.payerId!==id).map(e=>({...e,participantIds:e.participantIds.filter(pid=>pid!==id)})).filter(e=>e.participantIds.length);if(state.currentUserId===id)state.currentUserId=state.members[0].id;render();showToast(`已刪除 ${target.name}`)}
function buildReport(){const calc=calculations(),categories={};state.expenses.forEach(e=>categories[e.category]=(categories[e.category]||0)+e.amount);return{id:crypto.randomUUID(),name:state.tripName,archivedAt:new Date().toISOString(),total:calc.total,expenseCount:state.expenses.length,members:structuredClone(state.members),expenses:structuredClone(state.expenses),categories,paid:calc.paid}}
async function renderHistory(){$('historyList').innerHTML='<div class="all-settled">讀取資料庫中…</div>';try{const reports=await TripDatabase.all();$('historyList').innerHTML=reports.length?reports.map(report=>{const categories=Object.entries(report.categories||{}).sort((a,b)=>b[1]-a[1]);return `<article class="report-card"><div class="report-heading"><div><h3>${escapeHtml(report.name)}</h3><p>${new Date(report.archivedAt).toLocaleString('zh-TW')} · ${report.members.length} 位成員 · ${report.expenseCount} 筆</p></div><strong>${money(report.total)}</strong></div><div class="report-bars">${categories.map(([key,value])=>`<div><span>${categoryMeta[key]?.[0]||'其他'}</span><i><b style="width:${report.total?value/report.total*100:0}%"></b></i><em>${money(value)}</em></div>`).join('')||'<p>沒有花費資料</p>'}</div><div class="report-members">${report.members.map((m,i)=>`<span><b style="background:${colors[i%colors.length]}">${escapeHtml(initials(m.name))}</b>${escapeHtml(m.name)} ${money(report.paid[m.id]||0)}</span>`).join('')}</div><button class="report-delete" data-delete-report="${report.id}">刪除報表</button></article>`}).join(''):'<div class="empty-state"><span>▤</span><h3>還沒有歷史報表</h3><p>封存目前旅程後，小報表會保存在這裡。</p></div>'}catch{$('historyList').innerHTML='<div class="all-settled negative">資料庫讀取失敗，請確認瀏覽器允許網站儲存資料。</div>'}}
$('openExpenseButton').onclick=()=>{$('expenseForm').reset();fillFormMembers();$('expenseDialog').showModal();setTimeout(()=>$('expenseTitle').focus(),50)};$('openMemberButton').onclick=()=>{$('memberForm').reset();$('memberDialog').showModal();setTimeout(()=>$('memberName').focus(),50)};$('openHistoryButton').onclick=()=>{$('historyDialog').showModal();renderHistory()};document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$(button.dataset.close).close());
$('expenseForm').onsubmit=e=>{e.preventDefault();const participantIds=[...document.querySelectorAll('input[name="participants"]:checked')].map(input=>input.value);if(!participantIds.length){showToast('請至少選擇一位分攤成員');return}state.expenses.push({id:crypto.randomUUID(),title:$('expenseTitle').value.trim(),amount:Number($('expenseAmount').value),payerId:$('expensePayer').value,participantIds,category:$('expenseCategory').value,createdAt:new Date().toISOString()});$('expenseDialog').close();render();showToast('花費已加入共同帳本')};
$('memberForm').onsubmit=e=>{e.preventDefault();const name=$('memberName').value.trim();if(!name)return;state.members.push({id:crypto.randomUUID(),name});$('memberDialog').close();render();showToast(`${name} 已加入旅程`)};
$('expenseList').onclick=e=>{const b=e.target.closest('[data-delete-expense]');if(b)deleteExpense(b.dataset.deleteExpense)};$('memberList').onclick=e=>{const b=e.target.closest('[data-delete-member]');if(b&&!b.disabled)deleteMember(b.dataset.deleteMember)};
$('archiveTripButton').onclick=async()=>{if(!state.expenses.length){showToast('目前沒有花費可以封存');return}try{await TripDatabase.save(buildReport());await renderHistory();showToast('目前旅程已封存至歷史資料庫')}catch{showToast('封存失敗，請確認瀏覽器儲存權限')}};
$('historyList').onclick=async e=>{const b=e.target.closest('[data-delete-report]');if(!b||!confirm('確定永久刪除這份歷史報表嗎？'))return;await TripDatabase.remove(b.dataset.deleteReport);await renderHistory();showToast('歷史報表已刪除')};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;renderExpenses()});$('tripName').addEventListener('blur',()=>{state.tripName=$('tripName').textContent.trim()||'未命名旅程';render()});$('tripName').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.target.blur()}});
$('copySettlementButton').onclick=async()=>{const list=settlements(calculations().balance),text=list.map(s=>`${member(s.from).name} → ${member(s.to).name}：${money(s.amount)}`).join('\n');try{await navigator.clipboard.writeText(`${state.tripName}｜結算結果\n${text}`);showToast('結算結果已複製')}catch{showToast('瀏覽器不允許複製，請改用 HTTPS 開啟')}};$('resetButton').onclick=()=>{if(confirm('要清除目前資料並恢復示範內容嗎？（歷史報表不受影響）')){state=structuredClone(demoState);render();showToast('已恢復示範資料')}};render();
