(() => {
  let stopTripListener=null;
  const baseRenderMembers=renderMembers;
  renderMembers=calc=>{baseRenderMembers(calc);document.querySelectorAll('#memberList .member').forEach((row,index)=>{const item=state.members[index];if(!item)return;const info=row.querySelector('.member-info');if(item.email)info.insertAdjacentHTML('beforeend',`<small class="member-email">${escapeHtml(item.email)} · ${item.status==='accepted'?'已連結 Google':'等待接受邀請'}</small>`);const remove=row.querySelector('[data-delete-member]');if(remove&&item.linkedUid){remove.disabled=true;remove.title='已連結的 Google 成員需由帳本管理功能移除'}})};
  $('memberForm').onsubmit=async e=>{e.preventDefault();const name=$('memberName').value.trim(),email=$('memberEmail').value.trim().toLowerCase(),user=window.FirebaseService?.currentUser();if(!name)return;if(user&&email){try{await FirebaseService.syncNow(getWorkspace());const result=await FirebaseService.inviteMember(state.id,name,email);const latest=await FirebaseService.loadCurrent();if(latest)applyWorkspace(latest);$('memberDialog').close();$('inviteResultUrl').value=result.inviteUrl;$('inviteResultDialog').showModal();showToast(`已邀請 ${name}`)}catch(error){showToast(error.message?.replace('FirebaseError: ','')||'邀請建立失敗')}return}state.members.push({id:crypto.randomUUID(),name,email:email||'',status:email?'pending':'local'});$('memberDialog').close();render();showToast(email?'請登入 Google 帳號後再寄送邀請':`${name} 已加入本機帳本`)};
  $('copyInviteButton').onclick=async()=>{try{await navigator.clipboard.writeText($('inviteResultUrl').value);showToast('邀請連結已複製')}catch{$('inviteResultUrl').select();document.execCommand('copy')}};
  window.addEventListener('aa-auth-change',async event=>{stopTripListener?.();if(!event.detail.user)return;setTimeout(()=>{stopTripListener=FirebaseService.listenTrips(latest=>{if(latest.trips.some(trip=>trip.id===workspace.activeTripId))latest.activeTripId=workspace.activeTripId;applyWorkspace(latest)})},1200);const token=new URLSearchParams(location.search).get('invite');if(!token)return;try{await FirebaseService.acceptInvite(token);const latest=await FirebaseService.loadCurrent();if(latest){applyWorkspace(latest);showDashboard()}history.replaceState({},'',location.pathname);showToast('邀請已接受，你現在可以共同記帳')}catch(error){showToast(error.message?.replace('FirebaseError: ','')||'無法接受這份邀請')}});
  const token=new URLSearchParams(location.search).get('invite');if(token&&!FirebaseService.currentUser()){$('loginButton').textContent='登入並接受行程邀請';showToast('請使用受邀的 Google 帳號登入')}
  render();
})();
