const WORKSPACE_KEY='together-aa-workspace-v1';
let workspace=loadWorkspace();
function createTrip(name,startDate='',endDate=''){return{id:crypto.randomUUID(),tripName:name,startDate,endDate,currentUserId:'owner',members:[{id:'owner',name:'你'}],expenses:[],createdAt:new Date().toISOString()}}
function repairWorkspace(saved){const seen=new Set();saved.trips=saved.trips.filter(trip=>{if(!trip?.id||seen.has(trip.id))return false;seen.add(trip.id);return true});if(!saved.trips.some(trip=>trip.id===saved.activeTripId))saved.activeTripId=saved.trips[0]?.id;return saved}
function loadWorkspace(){try{const saved=JSON.parse(localStorage.getItem(WORKSPACE_KEY));if(saved?.trips?.length)return repairWorkspace(saved)}catch{}const migrated={...structuredClone(state),id:crypto.randomUUID(),startDate:'2026-08-22',endDate:'2026-08-24',createdAt:new Date().toISOString()};return{version:1,activeTripId:migrated.id,trips:[migrated]}}
function activeTrip(){return workspace.trips.find(trip=>trip.id===workspace.activeTripId)||workspace.trips[0]}
function syncActive(){const index=workspace.trips.findIndex(trip=>trip.id===workspace.activeTripId);if(index>=0)workspace.trips[index]=structuredClone(state)}
function saveWorkspace(){syncActive();localStorage.setItem(WORKSPACE_KEY,JSON.stringify(workspace))}
function getWorkspace(){syncActive();return structuredClone(workspace)}
function applyWorkspace(next){if(!next?.trips?.length)return false;workspace=next;workspace.activeTripId=workspace.activeTripId||workspace.trips[0].id;state=structuredClone(activeTrip());localStorage.setItem(WORKSPACE_KEY,JSON.stringify(workspace));render();renderDashboard();return true}
const originalSaveState=saveState;saveState=()=>{originalSaveState();saveWorkspace()};
state=structuredClone(activeTrip());
function dateRange(trip){const format=value=>value?new Date(`${value}T00:00:00`).toLocaleDateString('zh-TW',{month:'short',day:'numeric'}):'';return trip.startDate?`${format(trip.startDate)}${trip.endDate?` — ${format(trip.endDate)}`:''}`:'未設定日期'}
function showDashboard(){syncActive();renderDashboard();$('tripView').hidden=true;$('dashboardView').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
function openTrip(id,skipCurrentSync=false){if(!skipCurrentSync)syncActive();workspace.activeTripId=id;state=structuredClone(activeTrip());saveWorkspace();$('dashboardView').hidden=true;$('tripView').hidden=false;render();window.scrollTo({top:0,behavior:'smooth'})}
function renderDashboard(){syncActive();const total=workspace.trips.reduce((sum,trip)=>sum+trip.expenses.reduce((s,e)=>s+Number(e.amount||0),0),0);$('tripTotalCount').textContent=workspace.trips.length;$('allTripsAmount').textContent=money(total);$('tripCardGrid').innerHTML=workspace.trips.map((trip,index)=>{const amount=trip.expenses.reduce((sum,e)=>sum+Number(e.amount||0),0);return `<article class="trip-card" data-open-trip="${trip.id}"><div class="trip-card-top"><span class="trip-card-icon" style="background:${colors[index%colors.length]}">${escapeHtml(initials(trip.tripName))}</span><button data-delete-trip="${trip.id}" title="刪除行程">×</button></div><h3>${escapeHtml(trip.tripName)}</h3><p>${dateRange(trip)} · ${trip.members.length} 位成員</p><div><strong>${money(amount)}</strong><span>${trip.expenses.length} 筆花費 →</span></div></article>`}).join('')+`<button class="new-trip-card" id="emptyTripButton" type="button"><b>＋</b><span>建立另一個帳本</span></button>`;$('emptyTripButton').onclick=openCreateTrip}
function openCreateTrip(){$('tripForm').reset();$('tripDialog').showModal();setTimeout(()=>$('newTripName').focus(),50)}
$('openTripButton').onclick=openCreateTrip;$('backToDashboard').onclick=showDashboard;$('homeButton').onclick=e=>{e.preventDefault();showDashboard()};
$('tripForm').onsubmit=e=>{e.preventDefault();syncActive();const trip=createTrip($('newTripName').value.trim(),$('newTripStart').value,$('newTripEnd').value);const untouchedDemo=workspace.trips.length===1&&workspace.trips[0].tripName==='台南週末小旅行'&&workspace.trips[0].expenses?.every(item=>['e1','e2','e3','e4'].includes(item.id));workspace.trips=untouchedDemo?[trip]:[...workspace.trips,trip];workspace.activeTripId=trip.id;$('tripDialog').close();openTrip(trip.id,true);showToast('新帳本已建立')};
$('tripCardGrid').onclick=e=>{const remove=e.target.closest('[data-delete-trip]');if(remove){e.stopPropagation();if(workspace.trips.length===1){showToast('至少需要保留一個帳本');return}const trip=workspace.trips.find(t=>t.id===remove.dataset.deleteTrip);if(confirm(`確定刪除「${trip.tripName}」及其中所有花費嗎？建議先封存報表。`)){workspace.trips=workspace.trips.filter(t=>t.id!==trip.id);if(workspace.activeTripId===trip.id)workspace.activeTripId=workspace.trips[0].id;state=structuredClone(activeTrip());saveWorkspace();window.FirebaseService?.saveCurrent(getWorkspace());renderDashboard();showToast('行程已刪除')}return}const card=e.target.closest('[data-open-trip]');if(card)openTrip(card.dataset.openTrip)};
const baseRender=render;render=()=>{baseRender();if($('tripDate'))$('tripDate').textContent=dateRange(state)};
render();showDashboard();
